<?php

namespace App;

use ApiPlatform\Metadata\ApiResource;
use App\Shared\Symfony\DependencyInjection\CompilerPass\ApiPlatform\AttributeResourcePass;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\ChildDefinition;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        // @see https://github.com/api-platform/core/pull/6943
        $container->registerAttributeForAutoconfiguration(ApiResource::class, static function (ChildDefinition $definition): void {
            $definition->addTag('api_platform.resource');
            //$definition->addTag('container.excluded', ['source' => __FILE__]);
        });

        $container->addCompilerPass(new AttributeResourcePass());
        parent::build($container); // TODO: Change the autogenerated stub
    }
}
